config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#home"

  resources :missing_animals do
    member do
      delete :found
    end
  end

  resources :found_animals

  resources :chatrooms, only: [:show, :create, :destroy, :index ] do
    member do
      patch :accept
      patch :decline
    end
    resources :messages, only: :create
  end

  post 'start_chat/:user_id', to: 'chatrooms#start_chat', as: 'start_chat'
end

app/models/missing_animal.rb
class MissingAnimal < ApplicationRecord
  belongs_to :user
  has_many :chatrooms, dependent: :destroy
  has_one_attached :photo
  geocoded_by :lost_location
  after_validation :geocode, if: :will_save_change_to_lost_location?

  enum status: { missing: 0, found: 1 }

  after_initialize :set_default_status, if: :new_record?

  def set_default_status
    self.status ||= :missing
  end

  include PgSearch::Model
  pg_search_scope :search_by_multiple_attributes,
  against: [ :name, :species, :breed, :color, :description, :sex, :lost_location, :size ],
  using: {
    tsearch: { prefix: true, normalization: 2 }
  }
end

app/controllers/missing_animals_controller.rb
class MissingAnimalsController < ApplicationController
  def new
    @missing_animal = MissingAnimal.new
  end

  def create
    @missing_animal = MissingAnimal.new(missing_animal_params)
    @missing_animal.user = current_user

    if @missing_animal.save
      Rails.cache.delete('missing_animals')
      redirect_to missing_animal_path(@missing_animal)
    end
  end

  def show
    @missing_animal = MissingAnimal.find(params[:id])
    @user = @missing_animal.user
  end

  def edit
    @missing_animal = MissingAnimal.find(params[:id])
  end

  def update
    @missing_animal = MissingAnimal.find(params[:id])
    if @missing_animal.update(missing_animal_params)
      redirect_to missing_animal_path(@missing_animal)
    end
  end

  def destroy
    @missing_animal = MissingAnimal.find(params[:id])
    @missing_animal.update(status: :found) if params[:found]
    if @missing_animal.destroy
      redirect_to root_path
    else
      raise
    end
  end

  private

  def missing_animal_params
    params.require(:missing_animal).permit(:species, :age, :name, :breed, :lost_location, :date_lost, :sterilized, :size, :sex, :color, :description, :photo)
  end
end

app/helpers/missing_animals_helper.rb
module MissingAnimalsHelper
end

app/views/missing_animals/edit.html.erb
<h1>Edit info</h1>

<%= simple_form_for @missing_animal do |f| %>
  <%= f.input :species %>
  <%= f.input :age %>
  <%= f.input :name %>
  <%= f.input :breed %>
  <%= f.input :lost_location %>
  <%= f.input :date_lost, as: :date, start_year: Date.today.year - 5, end_year: Date.today.year %>
  <%= f.input :sterilized %>
  <%= f.input :size %>
  <%= f.input :color %>
  <%= f.input :sex %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/missing_animals/new.html.erb
<h1 class='text-center'>Report a missing animal</h1>

<div class="report-missing-animal-form">
  <%= simple_form_for @missing_animal do |f| %>
    <%= f.input :species, as: :select, collection: ['Dog', 'Cat', 'Bird', 'Hamster', 'Bunny', 'Other'], include_blank: false %>
    <%= f.input :age %>
    <%= f.input :name %>
    <%= f.input :breed %>
    <%= f.input :lost_location, input_html: { data: { controller: 'location-autocomplete' } } %>
    <%= f.input :date_lost, as: :date, start_year: Date.today.year - 5, end_year: Date.today.year %>
    <%= f.input :sterilized %>
    <%= f.input :size, as: :select, collection: ['Small', 'Medium', 'Large'], include_blank: false %>
    <%= f.input :color %>
    <%= f.input :sex, as: :select, collection: ['Male', 'Female'], include_blank: false %>
    <%= f.input :description %>
    <%= f.input :photo, as: :file %>
    <%= f.button :submit %>
  <% end %>
</div>

<%= link_to "Return home", root_path, class:'return-home-btn-missing-form' %>

app/views/missing_animals/show.html.erb
<h1>SHOW MISSING ANIMAL</h1>
<h3><%= link_to "Return home", root_path %></h3>

<%= @missing_animal.species %>
<%= @missing_animal.age %>
<%= @missing_animal.name %>
<%= @missing_animal.status %>
<%= image_tag url_for(@missing_animal.photo) if @missing_animal.photo.attached? %>

<% unless @missing_animal.user == current_user %>
  <%= button_to 'Start Chat', start_chat_path(user_id: @missing_animal.user.id, missing_animal_id: @missing_animal.id), method: :post %>
<% end %>

<% if @missing_animal.user == current_user %>
  <h6><%= link_to "Edit", edit_missing_animal_path(@missing_animal) %></h6>
  <%= link_to "Delete", missing_animal_path(@missing_animal), data: {turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
  <%= simple_form_for(@missing_animal, url: missing_animal_path(@missing_animal, found: true), method: :delete) do |f| %>
    <%= f.button :submit, "Has this mascot been reunited with its owner? Click here to update its status to FOUND and continue" %>
  <% end %>
<% end %>

<div class="container rounded-lg mt-5 mb-5">
  <iframe
    class="missing-animal-map"
    loading="lazy"
    allowfullscreen
    src="https://www.google.com/maps/embed/v1/place?key=<%= Rails.application.credentials.dig(:google_maps, :api_key) %>&q=<%= @missing_animal.lost_location %>">
  </iframe>
</div>



<h5>Reported by: <%= @user.first_name %></h5>