config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#home"

  resources :missing_animals do
    member do
      delete :found
    end
  end

  resources :found_animals

  resources :chatrooms, only: [:show, :create, :destroy, :index ] do
    member do
      patch :accept
      patch :decline
    end
    resources :messages, only: :create
  end

  post 'start_chat/:user_id', to: 'chatrooms#start_chat', as: 'start_chat'
end

app/models/found_animal.rb
class FoundAnimal < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  geocoded_by :found_location
  after_validation :geocode, if: :will_save_change_to_found_location?

  enum status: { missing: 0, found: 1 }

  after_initialize :set_default_status, if: :new_record?

  def set_default_status
    self.status ||= :missing
  end

  include PgSearch::Model
  pg_search_scope :search_by_name_and_species,
  against: [ :species, :breed, :found_location, :color, :description, :sex, :size ],
  using: {
    tsearch: { prefix: true, normalization: 2 }
  }
end

app/controllers/found_animals_controller.rb
class FoundAnimalsController < ApplicationController
  def new
    @found_animal = FoundAnimal.new
  end

  def create
    @found_animal = FoundAnimal.new(found_animal_params)
    @found_animal.user = current_user

    if @found_animal.save
      redirect_to found_animal_path(@found_animal)
    end
  end

  def show
    @found_animal = FoundAnimal.find(params[:id])
    @user = @found_animal.user
  end

  def edit
    @found_animal = FoundAnimal.find(params[:id])
  end

  def update
    @found_animal = FoundAnimal.find(params[:id])
    if @found_animal.update(found_animal_params)
      redirect_to found_animal_path(@found_animal)
    end
  end

  def destroy
    @found_animal = FoundAnimal.find(params[:id])
    if @found_animal.destroy
      redirect_to root_path
    end
  end

  private

  def found_animal_params
    params.require(:found_animal).permit(:species, :age, :name, :breed, :found_location, :found_date, :sterilized, :size, :sex, :color, :description, :photo)
  end
end

app/helpers/found_animals_helper.rb
module FoundAnimalsHelper
end

app/views/found_animals/edit.html.erb
<h1>Edit found animal info</h1>
<%= link_to "Return to show", found_animal_path(@found_animal) %>

<%= simple_form_for @found_animal do |f| %>
  <%= f.input :species %>
  <%= f.input :age %>
  <%= f.input :breed %>
  <%= f.input :found_location %>
  <%= f.input :found_date, as: :date, start_year: Date.today.year - 5, end_year: Date.today.year %>
  <%= f.input :sterilized %>
  <%= f.input :size %>
  <%= f.input :color %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/found_animals/new.html.erb
<h1>Report a found animal new</h1>
<%= link_to "Return home", root_path %>

<div class="report-found-animal-form">
  <%= simple_form_for @found_animal do |f| %>
    <%= f.input :species %>
    <%= f.input :age %>
    <%= f.input :breed %>
    <%= f.input :found_location, input_html: { data: { controller: 'location-autocomplete' } } %>
    <%= f.input :found_date, as: :date, start_year: Date.today.year - 5, end_year: Date.today.year %>
    <%= f.input :sterilized %>
    <%= f.input :size, as: :select, collection: ['Small', 'Medium', 'Large'], include_blank: false %>
    <%= f.input :color %>
    <%= f.input :sex, as: :select, collection: ['Male', 'Female'], include_blank: false %>
    <%= f.input :description %>
    <%= f.input :photo, as: :file %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/found_animals/show.html.erb
<h1>SHOW FOUND ANIMAL</h1>
<h3><%= link_to "Return home", root_path %></h3>

<%= @found_animal.species %>
<%= @found_animal.age %>
<%= @found_animal.breed %>
<%= @found_animal.found_location %>
<%= @found_animal.found_date %>
<%= @found_animal.sterilized %>
<%= @found_animal.size %>
<%= @found_animal.color %>
<%= @found_animal.description %>
<%= @found_animal.status %>
<%= image_tag url_for(@found_animal.photo) if @found_animal.photo.attached? %>

<% if @found_animal.user == current_user %>
  <h6><%= link_to "Edit", edit_found_animal_path(@found_animal) %></h6>
  <%= link_to "Delete", found_animal_path(@found_animal), data: {turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
  <%= simple_form_for(@found_animal, url: found_animal_path(@found_animal, found: true), method: :delete) do |f| %>
    <%= f.button :submit, "Has this mascot been reunited with its owner? Click here to update its status to LOST and continue" %>
  <% end %>
<% end %>

<% unless @found_animal.user == current_user %>
  <%= button_to 'Start Chat', start_chat_path(@found_animal.user.id), method: :post %>
<% end %>

<div class="container rounded-lg mt-5 mb-5">
  <iframe
    class="missing-animal-map"
    loading="lazy"
    allowfullscreen
    src="https://www.google.com/maps/embed/v1/place?key=<%= Rails.application.credentials.dig(:google_maps, :api_key) %>&q=<%= @found_animal.found_location %>">
  </iframe>
</div>

<h5>Reported by: <%= @user.first_name %></h5>