config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#home"

  resources :missing_animals do
    member do
      delete :found
    end
  end

  resources :found_animals

  resources :chatrooms, only: [:show, :create, :destroy, :index ] do
    member do
      patch :accept
      patch :decline
    end
    resources :messages, only: :create
  end

  post 'start_chat/:user_id', to: 'chatrooms#start_chat', as: 'start_chat'
end

app/views/pages/_animal.html.erb
<div class="animal-card border p-3">
  <h2 class="animal-name">Name: <%= link_to (animal.respond_to?(:name) ? animal.name : 'No Name'), send(path_method, animal), class:'text-decoration-none' %></h2>
  <div class="animal-details">
    <h6>Species: <%= animal.species %></h6>
    <h6>Age: <%= animal.age %></h6>
    <h6>Breed: <%= animal.breed %></h6>
    <h6>Location: <%= animal.respond_to?(:lost_location) ? animal.lost_location : animal.found_location %></h6>
    <h6>Date: <%= animal.respond_to?(:date_lost) ? animal.date_lost : animal.found_date %></h6>
    <h6>Sterilized: <%= animal.sterilized %></h6>
    <h6>Sex: <%= animal.sex %></h6>
    <h6>Size: <%= animal.size %></h6>
    <h6>Color: <%= animal.color %></h6>
    <h6>Description: <%= animal.description %></h6>
    <h6>Reported by: <%= animal.user.first_name %></h6>
  </div>
  <%= image_tag url_for(animal.photo), size: "200x200", class: "animal-photo" if photo_attached?(animal) %>
  <div class="container rounded-lg mt-5 mb-5 map-container">
  <iframe
  class="missing-animal-map"
  loading="lazy"
  allowfullscreen
  src="https://www.google.com/maps/embed/v1/place?key=<%= Rails.application.credentials.dig(:google_maps, :api_key) %>&q=<%= animal.respond_to?(:lost_location) ? animal.lost_location : animal.found_location %>">
</iframe>
</div>
</div>

app/views/pages/_animal_list.html.erb
<div>
  <h1 class="text-center"><%= title %>:</h1>
  <% if animals.present? %>
    <% animals.each do |animal| %>
      <%= render 'animal', animal: animal, path_method: path_method %>
    <% end %>
  <% else %>
    <p class="text-center">No <%= title.downcase %> to display.</p>
  <% end %>
</div>

app/views/pages/_chat_invitation.html.erb
<% other_user = chatroom.other_user(current_user) %>
<div class='border p-4 my-4 chat-invitation'>
  <h3 class='mx-3 mb-3 invitation-details'>You got invited to start a chat with <%= other_user.first_name %> about your report of <%= chatroom.missing_animal.name %> </h3>
  <%= button_to 'Accept Chat', accept_chatroom_path(chatroom), method: :patch, class:"btn btn-success accept-chat-button mr-2" %>
  <%= button_to 'Decline Chat', decline_chatroom_path(chatroom), method: :patch, data: { confirm: 'Are you sure?' }, class:"btn btn-danger decline-chat-button" %>
</div>

app/views/pages/_chatroom.html.erb
<% other_user = chatroom.other_user(current_user) %>
<% if chatroom.accepted? %>
  <%= link_to other_user.first_name, chatroom_path(chatroom), class:'active-chat-link btn btn-primary mb-3' %>
<% elsif chatroom.pending? && chatroom.invited?(current_user) %>
  <%= render 'chat_invitation', chatroom: chatroom, other_user: other_user %>
<% end %>

app/views/pages/home.html.erb
<div class="container py-5">
  <h1 class="text-center mb-5 home-title">HOME PAGE</h1>
  <h2 class="text-center mb-5 user-name"><%= current_user.first_name %></h2>

  <div class="row p-3 d-flex align-items-center mt-5 action-section">
    <div class="col-md-4 text-center mb-4">
      <%= link_to "Report a missing mascot", new_missing_animal_path, class: "btn btn-warning missing-button" %>
    </div>
    <div class="col-md-4 text-center mb-4">
      <%= form_with url: root_path, method: :get, class: 'form-inline justify-content-center' do %>
        <%= text_field_tag :query, params[:query], placeholder: "Search for mascots", class: 'form-control search-bar-input' %>
      <% end %>
    </div>
    <div class="col-md-4 text-center mb-4">
      <%= link_to "Found an animal?", new_found_animal_path, class: "btn btn-success missing-button" %>
    </div>
  </div>

  <div class="row animal-list-section">
    <div class="col-md-6 mb-5">
      <% cache 'missing_animals' do %>
        <%= render 'animal_list', title: 'Missing mascots', animals: @missing_animals, path_method: :missing_animal_path %>
      <% end %>
    </div>
    <div class="col-md-6 mb-5">
      <% cache 'found_animals' do %>
        <%= render 'animal_list', title: 'Found mascots', animals: @found_animals, path_method: :found_animal_path %>
      <% end %>
    </div>
  </div>
</div>